//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
)

type TaskTags struct {
	TaskID uuid.UUID `sql:"primary_key"`
	Tag    string    `sql:"primary_key"`
}
