//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Tasks struct {
	ID          uuid.UUID `sql:"primary_key"`
	Title       string
	Description string
	SourceID    string
	SourceURL   string
	SourceHash  string
	Type        int32
	Difficulty  int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
