//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Examples = newExamplesTable("public", "examples", "")

type examplesTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	TaskID      postgres.ColumnString
	Input       postgres.ColumnString
	Output      postgres.ColumnString
	Explanation postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type ExamplesTable struct {
	examplesTable

	EXCLUDED examplesTable
}

// AS creates new ExamplesTable with assigned alias
func (a ExamplesTable) AS(alias string) *ExamplesTable {
	return newExamplesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ExamplesTable with assigned schema name
func (a ExamplesTable) FromSchema(schemaName string) *ExamplesTable {
	return newExamplesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ExamplesTable with assigned table prefix
func (a ExamplesTable) WithPrefix(prefix string) *ExamplesTable {
	return newExamplesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ExamplesTable with assigned table suffix
func (a ExamplesTable) WithSuffix(suffix string) *ExamplesTable {
	return newExamplesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newExamplesTable(schemaName, tableName, alias string) *ExamplesTable {
	return &ExamplesTable{
		examplesTable: newExamplesTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newExamplesTableImpl("", "excluded", ""),
	}
}

func newExamplesTableImpl(schemaName, tableName, alias string) examplesTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		TaskIDColumn      = postgres.StringColumn("task_id")
		InputColumn       = postgres.StringColumn("input")
		OutputColumn      = postgres.StringColumn("output")
		ExplanationColumn = postgres.StringColumn("explanation")
		allColumns        = postgres.ColumnList{IDColumn, TaskIDColumn, InputColumn, OutputColumn, ExplanationColumn}
		mutableColumns    = postgres.ColumnList{TaskIDColumn, InputColumn, OutputColumn, ExplanationColumn}
		defaultColumns    = postgres.ColumnList{IDColumn}
	)

	return examplesTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		TaskID:      TaskIDColumn,
		Input:       InputColumn,
		Output:      OutputColumn,
		Explanation: ExplanationColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
