//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Tasks = newTasksTable("public", "tasks", "")

type tasksTable struct {
	postgres.Table

	// Columns
	ID          postgres.ColumnString
	Title       postgres.ColumnString
	Description postgres.ColumnString
	SourceID    postgres.ColumnString
	SourceURL   postgres.ColumnString
	SourceHash  postgres.ColumnString
	Type        postgres.ColumnInteger
	Difficulty  postgres.ColumnInteger
	CreatedAt   postgres.ColumnTimestampz
	UpdatedAt   postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TasksTable struct {
	tasksTable

	EXCLUDED tasksTable
}

// AS creates new TasksTable with assigned alias
func (a TasksTable) AS(alias string) *TasksTable {
	return newTasksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TasksTable with assigned schema name
func (a TasksTable) FromSchema(schemaName string) *TasksTable {
	return newTasksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TasksTable with assigned table prefix
func (a TasksTable) WithPrefix(prefix string) *TasksTable {
	return newTasksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TasksTable with assigned table suffix
func (a TasksTable) WithSuffix(suffix string) *TasksTable {
	return newTasksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTasksTable(schemaName, tableName, alias string) *TasksTable {
	return &TasksTable{
		tasksTable: newTasksTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newTasksTableImpl("", "excluded", ""),
	}
}

func newTasksTableImpl(schemaName, tableName, alias string) tasksTable {
	var (
		IDColumn          = postgres.StringColumn("id")
		TitleColumn       = postgres.StringColumn("title")
		DescriptionColumn = postgres.StringColumn("description")
		SourceIDColumn    = postgres.StringColumn("source_id")
		SourceURLColumn   = postgres.StringColumn("source_url")
		SourceHashColumn  = postgres.StringColumn("source_hash")
		TypeColumn        = postgres.IntegerColumn("type")
		DifficultyColumn  = postgres.IntegerColumn("difficulty")
		CreatedAtColumn   = postgres.TimestampzColumn("created_at")
		UpdatedAtColumn   = postgres.TimestampzColumn("updated_at")
		allColumns        = postgres.ColumnList{IDColumn, TitleColumn, DescriptionColumn, SourceIDColumn, SourceURLColumn, SourceHashColumn, TypeColumn, DifficultyColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns    = postgres.ColumnList{TitleColumn, DescriptionColumn, SourceIDColumn, SourceURLColumn, SourceHashColumn, TypeColumn, DifficultyColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns    = postgres.ColumnList{IDColumn, DifficultyColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return tasksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Title:       TitleColumn,
		Description: DescriptionColumn,
		SourceID:    SourceIDColumn,
		SourceURL:   SourceURLColumn,
		SourceHash:  SourceHashColumn,
		Type:        TypeColumn,
		Difficulty:  DifficultyColumn,
		CreatedAt:   CreatedAtColumn,
		UpdatedAt:   UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
