//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TaskTags = newTaskTagsTable("public", "task_tags", "")

type taskTagsTable struct {
	postgres.Table

	// Columns
	TaskID postgres.ColumnString
	Tag    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type TaskTagsTable struct {
	taskTagsTable

	EXCLUDED taskTagsTable
}

// AS creates new TaskTagsTable with assigned alias
func (a TaskTagsTable) AS(alias string) *TaskTagsTable {
	return newTaskTagsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TaskTagsTable with assigned schema name
func (a TaskTagsTable) FromSchema(schemaName string) *TaskTagsTable {
	return newTaskTagsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TaskTagsTable with assigned table prefix
func (a TaskTagsTable) WithPrefix(prefix string) *TaskTagsTable {
	return newTaskTagsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TaskTagsTable with assigned table suffix
func (a TaskTagsTable) WithSuffix(suffix string) *TaskTagsTable {
	return newTaskTagsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTaskTagsTable(schemaName, tableName, alias string) *TaskTagsTable {
	return &TaskTagsTable{
		taskTagsTable: newTaskTagsTableImpl(schemaName, tableName, alias),
		EXCLUDED:      newTaskTagsTableImpl("", "excluded", ""),
	}
}

func newTaskTagsTableImpl(schemaName, tableName, alias string) taskTagsTable {
	var (
		TaskIDColumn   = postgres.StringColumn("task_id")
		TagColumn      = postgres.StringColumn("tag")
		allColumns     = postgres.ColumnList{TaskIDColumn, TagColumn}
		mutableColumns = postgres.ColumnList{}
		defaultColumns = postgres.ColumnList{}
	)

	return taskTagsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TaskID: TaskIDColumn,
		Tag:    TagColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
